hyperparameters:
  num_epochs: 50
  learning_rate: 3e-4
  train_batch_size: 8
  val_batch_size: 1
  val_frequency: 1
  log_frequency: 10
  batch_size: 8
  gamma: 0.1
  step_size: 10
  patience: 5
  factor: 0.1

paths:
  data_root: "./datasets"
  ckpt_dir: "./checkpoints"
  out_dir: "prediction"

terminal:
  BOLD : "\033[1m"
  CYAN : "\033[96m"
  YELLOW : "\033[93m"
  GREEN : "\033[92m"
  RED : "\033[91m"
  RESET : "\033[0m"